[application]

# App (Project) Name
name = "rustmameui"

[web.app]

# HTML title tag content
title = "rustmameui"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
resources = [ 
    "/assets/tabs.css" 
]